cross_button='//span[@class="commonModal__close"]'
hotel_link= '//a[@href="https://www.makemytrip.com/hotels/"]'
max_room_text= '//span[text()="Upto 4 Rooms"]'
city_field= '//input[@id="city"]'
input_city_field= '//input[@placeholder="Where do you want to stay?"]'
check_in_date_field= '//p[@data-cy="checkInDate"]'
check_in_date= '//div[@class="DayPicker-Caption"]/child::div[contains(text(),"Month")]/parent::div/following-sibling::div[@class="DayPicker-Body"]//div[@class="DayPicker-Week"]/child::div[text()="Date"]'
check_out_date= '//div[@class="DayPicker-Caption"]/child::div[contains(text(),"Month")]/parent::div/following-sibling::div[@class="DayPicker-Body"]//div[@class="DayPicker-Week"]/child::div[text()="Date"]'
room_field= '//div[@class="gstSlct"]/span[@data-testid="room_count"]'
input_room_field= '//li[@data-cy="GuestSelect$$_323"][RoomCount]'
children_field= '//div[@class="gstSlct"]/span[@data-testid="children_count"]'
input_children_field= '//li[@data-cy="GuestSelect$$_323"][ChildrenCount]'
child_age_field= '//div[@class="gstSlct"]/span[@data-testid="child_count"]'
input_child_age_field= '//li[@data-cy="GuestSelect$$_323"][ChildAge]'
apply_button= '//button[text()="Apply"]'
search_button= '//button[text()="Search"]'
city_name= '//input[@id="city"]'
check_in_date_on_search_result= '//input[@id="checkin"]'
check_out_date_on_search_result= '//input[@id="checkout"]'
guest_details= '//input[@id="guest"]'
total_hotel_count= '//h1[@class="font24 latoBlack whiteText appendTop10"]'
city= '(//div[@class="hw__searchedResultChild clickable appendLeft5"])[1]'
prices='//div/p[@class="priceText latoBlack font22 blackText appendBottom5"]'
checkbox_price_range= '//label[@for="₹ 0 - ₹ 2500"]'
